-- Schema do Supabase para o MedCare-CLI
-- Autor: Nelson Ribeiro Felix

create table if not exists public.medications (
    id bigint generated by default as identity primary key,
    name text not null,
    dosage text not null,
    time time not null,
    created_at timestamptz not null default now()
);

alter table public.medications enable row level security;

create policy "Permitir leitura pública controlada de medicamentos"
on public.medications
for select
using (true);

create policy "Permitir cadastro público controlado de medicamentos"
on public.medications
for insert
with check (true);

create policy "Permitir remoção pública controlada de medicamentos"
on public.medications
for delete
using (true);
